modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
logoFile = "${mod_icon}"

[[dependencies.${mod_id}]]
modId = "${loader}"
${mnd}
versionRange="[${mfd},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
${mnd}
versionRange="${mod_versionRangeForge}"
ordering="NONE"
side="BOTH"